# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf5d91779dc8b863201e7417511f54304fe51b2e0d09868c2048ed1b9736bd285143fcdad32b782ee35f5e0a352f071bf3ac51ed0db5f0514010558e96ac2759

test:
  secret_key_base: c3bddc51de04c35fbac7f012b4e3ea43398a0a11278212f8a626eba5e1b55a045fa3e423cf78bfa4c046ba2d055b51424fa5ec9063306b434db96ef5cc7dc51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
